import Header from '../../components/Header';
import Footer from '../../components/Footer';
import styles from '../../styles/LegalPage.module.css';

const PrivacyPolicyPage = () => {
  return (
    <div className={styles.pageContainer}>
      <Header />
      <main className={styles.mainContent}>
        <h1 className={styles.title}>Privacy Policy</h1>
        <p>
          Welcome to Ideo Graphics. This Privacy Policy describes Our policies and procedures on the collection, 
          use and disclosure of Your information when You use our website and services, and tells You 
          about Your privacy rights and how the law protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to 
          the collection and use of information in accordance with this Privacy Policy.
        </p>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Interpretation and Definitions</h2>
          <h3 className={styles.subSectionTitle}>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the 
            following conditions. The following definitions shall have the same meaning regardless of 
            whether they appear in singular or in plural.
          </p>
          <h3 className={styles.subSectionTitle}>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className={styles.list}>
            <li>
              <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) 
              refers to Ideo Graphics, 5H1, BCG Residency Towers, Opp. CSEZ, Seaport-Airport Road, Kakkanad, Kochi, Kerala - 682037.
            </li>
            <li>
              <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a 
              website, containing the details of Your browsing history on that website among its many uses.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Website.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service 
              or from the Service infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <strong>Website</strong> refers to Ideo Graphics, accessible from [Your Website URL]
            </li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Collecting and Using Your Personal Data</h2>
          <h3 className={styles.subSectionTitle}>Types of Data Collected</h3>
          <h4>Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable 
            information that can be used to contact or identify You. Personally identifiable information 
            may include, but is not limited to:
          </p>
          <ul className={styles.list}>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h4>Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service.</p>
          <p>
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), 
            browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, 
            the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
        </section>
        
        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Use of Your Personal Data</h2>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul className={styles.list}>
            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
            <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
            <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
            <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            <li>To provide You with news, special offers and general information about other goods, services and events which we offer.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting 
            the new Privacy Policy on this page.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy 
            Policy are effective when they are posted on this page.
          </p>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className={styles.list}>
            <li>By email: info@ideogfx.com</li>
            <li>By phone number: +91 8921700822</li>
            <li>By mail: 5H1, BCG Residency Towers, Opp. CSEZ, Seaport-Airport Road, Kakkanad, Kochi, Kerala - 682037</li>
          </ul>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicyPage;
